-- ============================================================================
-- Role & Grants — least-privilege service role for the pipeline/dbt/BI
-- Run as ACCOUNTADMIN (role creation + user-role grant require it).
-- ============================================================================

CREATE ROLE IF NOT EXISTS FOOTBALL_ANALYTICS_ROLE
    COMMENT = 'Service role used by the ingestion pipeline, dbt, and BI dashboard';

-- Warehouse usage
GRANT USAGE ON WAREHOUSE FOOTBALL_ANALYTICS_WH TO ROLE FOOTBALL_ANALYTICS_ROLE;
GRANT OPERATE ON WAREHOUSE FOOTBALL_ANALYTICS_WH TO ROLE FOOTBALL_ANALYTICS_ROLE;

-- Database + schema usage
GRANT USAGE ON DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;

-- Full DML/DDL on all layers — the pipeline and dbt both need to create/replace
-- tables and views as models evolve. Scope is the FOOTBALL_ANALYTICS database only.
GRANT ALL ON ALL TABLES IN DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;
GRANT ALL ON ALL VIEWS IN DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;
GRANT ALL ON FUTURE VIEWS IN DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;
GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE FOOTBALL_ANALYTICS TO ROLE FOOTBALL_ANALYTICS_ROLE;

-- ----------------------------------------------------------------------------
-- Grant the role to your user. Replace <YOUR_SNOWFLAKE_USERNAME> before running,
-- or run this single line manually in Snowsight.
-- ----------------------------------------------------------------------------
-- GRANT ROLE FOOTBALL_ANALYTICS_ROLE TO USER <YOUR_SNOWFLAKE_USERNAME>;
